/// @description Draw the Perlin Noise

for (var _x = X; _x < room_width + X; _x+=SQUARE_SIZE) {
for (var _y = Y; _y < room_height + Y; _y+=SQUARE_SIZE) {
	
	var _humidity	= (noise_octave(SEED, _x/scale, _y/scale, OCTAVES));
	var _inlandness	= (noise_octave(SEED+1, _x/scale, _y/scale, OCTAVES));
	
	var _biome = get_biome(_humidity, _inlandness);
	draw_set_color(ds_map_find_value(_biome[0], "color"));
	
	draw_rectangle(_x-X, _y-Y, _x+SQUARE_SIZE-X, _y+SQUARE_SIZE-Y, false);
	
}}

// Gets the biome given an inlandness and a humidity (generated by perlin noise)
_biome = get_biome(
noise_octave(SEED, (mouse_x+X)/scale, (mouse_y+Y)/scale, OCTAVES),
noise_octave(SEED+1, (mouse_x+X)/scale, (mouse_y+Y)/scale, OCTAVES))

_biomeName = ds_map_find_value(_biome[0], "name");

_biomeColor = ds_map_find_value(_biome[0], "color");
draw_set_color(100000000-_biomeColor);
draw_text(mouse_x, mouse_y, _biomeName);